name: tweedekamer_monitor
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - ipython
  - jupyterlab
  - matplotlib
  - pandas
  - pip:
    - dlt[duckdb]
    - duckdb
    - dbt-duckdb
    - nbstripout
    - requests
    - xmlschema
    - lxml
    - streamlit
